[package]
name = "everything_bot2"
version = "0.0.1"
authors = ["JustANull <reid.levenick@gmail.com>"]

[dependencies]
fern = "0.3.*"
hyper = "0.6.*"
irc = "0.9.*"
lazy_static = "0.1.*"
log = "0.3.*"
regex = "0.1.*"
rustc-serialize = "0.3.*"
