[package]
name = "everything_bot"
version = "0.0.2"
authors = ["JustANull <reid.levenick@gmail.com>"]

[dependencies]
fern = "^0.3.5"
hyper = "=0.6.14"
irc = "^0.9.0"
lazy_static = "^0.1.15"
log = "^0.3.2"
regex = "^0.1.41"
rustc-serialize = "^0.3.16"
